### ISSUE TITLE
Rename radioConfig.py to radioConfig.py.example

### ISSUE THREAD

**Issue by chrissamuel** [mariocannistra/radio-astronomy-fftw#2]
Currently if you edit radioConfig.py to configure your location git will want to track those changes, and should the config file change in future you'll need to resolve that conflict.

It would be cleaner if the file in git was renamed to be radioConfig.py.example so that sites can copy it to be radioConfig.py and then modify it to suite.  Then when changes happen they can merge them by hand without disturbing the state of the git repository locally.

How does that sound?

All the best!
Chris

**Comment by mariocannistra** [comment]
Hello Chris.
This is a very good idea.
I just renamed the file as  radioConfig-example.py  because placing "example" as the final extension... my source editor no longer recognizes the source as Python and no longer colors the keyword/statements...

**Comment by chrissamuel** [comment]
Hi Mario,
That's great, your choice of name is a better idea!
All the best,
Chris
