### ISSUE TITLE
Suggested additions to .gitignore

### ISSUE THREAD

**Issue by chrissamuel** [mariocannistra/radio-astronomy-fftw#4]
Hi Mario,
One final idea from myself, when I go "git status" I see:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        Leap_Second.dat
        de421.bsp
        deltat.data
        deltat.preds
        jup310.bsp
        jup310.bsp.download
        radioConfig.py
```

It might be an idea to add them to .gitignore to stop git complaining.

All the best!
Chris

**Comment by mariocannistra** [comment]
Hello Chris.
Sorry for the long delay.  I had to leave behind my project for some time.
I did some improvements and also added your suggested list to gitignore.
mario

**Comment by chrissamuel** [comment]
Thanks Mario!  Not a problem, I quite understand.
Best of luck!
